<a href="https://colab.research.google.com/github/AkahndPratapSingh136/NLP/blob/main/TextRepresentation_FeatureExtraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# One Hot Encoding:
One hot encoding is a technique that we use to represent categorical variables as numerical values in a machine learning model.

The advantages of using one hot encoding include:
1. It allows the use of categorical variables in models that require numerical input.
2. It can improve model performance by providing more information to the model about the categorical variable.
3. It can help to avoid the problem of ordinality, which can occur when a categorical variable has a natural ordering (e.g. “small”, “medium”, “large”).

The disadvantages of using one hot encoding include:
1. It can lead to increased dimensionality, as a separate column is created for each category in the variable. This can make the model more complex and slow to train.
 
2. It can lead to sparse data, as most observations will have a value of 0 in most of the one-hot encoded columns.
 
3. It can lead to overfitting, especially if there are many categories in the variable and the sample size is relatively small.
 
4. One-hot-encoding is a powerful technique to treat categorical data, but it can lead to increased dimensionality, sparsity, and overfitting. It is important to use it cautiously and consider other methods such as ordinal encoding or binary encoding.

**class sklearn.feature_extraction.text.CountVectorizer**(*, input='content', encoding='utf-8', decode_error='strict', strip_accents=None, lowercase=True, preprocessor=None, tokenizer=None, stop_words=None, token_pattern='(?u)\b\w\w+\b', ngram_range=(1, 1), analyzer='word', max_df=1.0, min_df=1, max_features=None, vocabulary=None, binary=False, dtype=<class 'numpy.int64'> )

# Bag of Word(BOG):
Bag of words is a Natural Language Processing technique of text modelling. In technical terms, we can say that it is a method of feature extraction with text data. This approach is a simple and flexible way of extracting features from documents.

A bag of words is a representation of text that describes the occurrence of words within a document. We just keep track of word counts and disregard the grammatical details and the word order. It is called a “bag” of words because any information about the order or structure of words in the document is discarded. The model is only concerned with whether known words occur in the document, not where in the document.

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.DataFrame({'text':['people watch campusx', 'campusx watch campusx', 'people wirte comment', 'campusx write comment'],'output':[1,1,0,0]})

In [3]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people wirte comment       0
3  campusx write comment       0

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(stop_words=None)

In [17]:
bow=cv.fit_transform(df['text'])

In [18]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'wirte': 4, 'comment': 1, 'write': 5}


In [19]:
print(bow[0].toarray())

[[1 0 1 1 0 0]]


In [20]:
print(bow[1].toarray())

[[2 0 0 1 0 0]]


In [21]:
cv.transform(['campusx watch and write comment of campusx']).toarray()

array([[2, 1, 0, 1, 0, 1]])

# N-Grams:

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(2,2))

In [26]:
bow=cv.fit_transform(df['text'])

In [27]:
print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people wirte': 3, 'wirte comment': 5, 'campusx write': 1, 'write comment': 6}


In [28]:
print(bow[0].toarray())

[[0 0 1 0 1 0 0]]


In [29]:
print(bow[1].toarray())

[[1 0 0 0 1 0 0]]


In [30]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(1,2))

In [31]:
bow=cv.fit_transform(df['text'])

In [32]:
print(cv.vocabulary_)

{'people': 4, 'watch': 7, 'campusx': 0, 'people watch': 5, 'watch campusx': 8, 'campusx watch': 1, 'wirte': 9, 'comment': 3, 'people wirte': 6, 'wirte comment': 10, 'write': 11, 'campusx write': 2, 'write comment': 12}


In [33]:
print(bow[0].toarray())

[[1 0 0 0 1 1 0 1 1 0 0 0 0]]


In [34]:
print(bow[1].toarray())

[[2 1 0 0 0 0 0 1 1 0 0 0 0]]


In [36]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(1,3))

In [37]:
bow=cv.fit_transform(df['text'])

In [38]:
print(cv.vocabulary_)

{'people': 6, 'watch': 11, 'campusx': 0, 'people watch': 7, 'watch campusx': 12, 'people watch campusx': 8, 'campusx watch': 1, 'campusx watch campusx': 2, 'wirte': 13, 'comment': 5, 'people wirte': 9, 'wirte comment': 14, 'people wirte comment': 10, 'write': 15, 'campusx write': 3, 'write comment': 16, 'campusx write comment': 4}


In [39]:
print(bow[0].toarray())

[[1 0 0 0 0 0 1 1 1 0 0 1 1 0 0 0 0]]


**NOTE:**

ngram_range=(1,1) --> Unigrams(BOW)

ngram_range=(2,3) --> Bigrams

ngram_range=(3,3) --> Trigram

ngram_range=(1,2) --> Unigram+Bigram

ngram_range=(1,3) --> Unigram+Bigram+Trigram

and so on...

# Tf-Idf:
TF-IDF stands for Term Frequency Inverse Document Frequency of records. It can be defined as the calculation of how relevant a word in a series or corpus is to a text. The meaning increases proportionally to the number of times in the text a word appears but is compensated by the word frequency in the corpus (data-set).

Terminologies:

1. Term Frequency: In document d, the frequency represents the number of instances of a given word t. Therefore, we can see that it becomes more relevant when a word appears in the text, which is rational. Since the ordering of terms is not significant, we can use a vector to describe the text in the bag of term models. For each specific term in the paper, there is an entry with the value being the term frequency.
The weight of a term that occurs in a document is simply proportional to the term frequency.

  **tf(t,d) = count of t in d / number of words in d**

2. Document Frequency: This tests the meaning of the text, which is very similar to TF, in the whole corpus collection. The only difference is that in document d, TF is the frequency counter for a term t, while df is the number of occurrences in the document set N of the term t. In other words, the number of papers in which the word is present is DF.

  **df(t) = occurrence of t in documents**

3. Inverse Document Frequency: Mainly, it tests how relevant the word is. The key aim of the search is to locate the appropriate records that fit the demand. Since tf considers all terms equally significant, it is therefore not only possible to use the term frequencies to measure the weight of the term in the paper. First, find the document frequency of a term t by counting the number of documents containing the term:

  df(t) = N(t)

  where

  df(t) = Document frequency of a term t
  
  N(t) = Number of documents containing the term t 

4. Term frequency is the number of instances of a term in a single document only; although the frequency of the document is the number of separate documents in which the term appears, it depends on the entire corpus. Now let’s look at the definition of the frequency of the inverse paper. The IDF of the word is the number of documents in the corpus separated by the frequency of the text.

  **idf(t) = N/ df(t) = N/N(t)**

  The more common word is supposed to be considered less significant, but the element (most definite integers) seems too harsh. We then take the logarithm (with base 2) of the inverse frequency of the paper. So the if of the term t becomes:

  **idf(t) = log(N/ df(t))**

5. Computation: Tf-idf is one of the best metrics to determine how significant a term is to a text in a series or a corpus. tf-idf is a weighting system that assigns a weight to each word in a document based on its term frequency (tf) and the reciprocal document frequency (tf) (idf). The words with higher scores of weight are deemed to be more significant.
Usually, the tf-idf weight consists of two terms-

  Normalized Term Frequency (tf)
  
  Inverse Document Frequency (idf)
  
  **tf-idf(t, d) = tf(t, d) * idf(t)**
  
  In python tf-idf values can be computed using TfidfVectorizer() method in sklearn module.

In [40]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people wirte comment       0
3  campusx write comment       0

In [41]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ,
        0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ,
        0.        ],
       [0.        , 0.52640543, 0.52640543, 0.        , 0.66767854,
        0.        ],
       [0.44809973, 0.55349232, 0.        , 0.        , 0.        ,
        0.70203482]])

In [42]:
print(tfidf.idf_)

[1.22314355 1.51082562 1.51082562 1.51082562 1.91629073 1.91629073]


In [45]:
print(tfidf.get_feature_names_out())

['campusx' 'comment' 'people' 'watch' 'wirte' 'write']
